# Generated by Django 5.0.2 on 2025-07-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasesymptom',
            name='weight',
            field=models.IntegerField(default=1, help_text='The importance of the symptom for this disease (e.g., 1-10).'),
        ),
    ]
