# Generated by Django 5.0.2 on 2025-07-07 17:06

from django.db import migrations


DISEASES_DATA = {
    "Malaria": {
        "description": "A mosquito-borne infectious disease that affects humans and other animals.",
        "symptoms": {
            "Fever": 10,
            "Headache": 7,
            "Chills": 9,
            "Vomiting": 6,
            "Fatigue": 8,
            "Muscle pain": 7,
        },
        "treatments": [
            "Artemisinin-based combination therapies (ACTs) are the recommended treatment.",
            "Rest and drink plenty of fluids."
        ]
    },
    "Typhoid Fever": {
        "description": "A bacterial infection that can lead to a high fever, diarrhea, and vomiting.",
        "symptoms": {
            "High fever": 10,
            "Headache": 8,
            "Stomach pain": 8,
            "Constipation or Diarrhea": 7,
            "Rash": 6,
            "Weakness": 9,
        },
        "treatments": [
            "Antibiotic therapy is the only effective treatment for typhoid fever.",
            "Drink plenty of water to prevent dehydration."
        ]
    },
    "Stomach Ulcer": {
        "description": "Sores that develop on the lining of the stomach.",
        "symptoms": {
            "Burning stomach pain": 10,
            "Bloating": 7,
            "Heartburn": 8,
            "Nausea": 6,
            "Vomiting": 5,
        },
        "treatments": [
            "Proton pump inhibitors (PPIs) to reduce stomach acid.",
            "H2 receptor blockers to reduce stomach acid.",
            "Avoid spicy foods, alcohol, and smoking."
        ]
    },
    "Diarrhea": {
        "description": "Loose, watery stools three or more times in a day.",
        "symptoms": {
            "Loose stools": 10,
            "Abdominal cramps": 8,
            "Fever": 6,
            "Nausea": 7,
            "Bloating": 7,
        },
        "treatments": [
            "Drink plenty of liquids, including water, broths, and juices.",
            "Oral rehydration solutions (ORS) are recommended.",
            "Avoid dairy products, fatty foods, and high-fiber foods for a few days."
        ]
    },
    "Yellow Fever": {
        "description": "A viral infection spread by a particular species of mosquito.",
        "symptoms": {
            "Fever": 10,
            "Headache": 9,
            "Jaundice": 9,
            "Muscle pain": 8,
            "Vomiting": 7,
            "Bleeding": 6,
        },
        "treatments": [
            "No specific treatment for yellow fever. Treatment is symptomatic.",
            "Rest, drink fluids, and use pain relievers.",
            "Hospitalization may be necessary for severe cases."
        ]
    }
}

def populate_initial_data(apps, schema_editor):
    Symptom = apps.get_model('expert_system_app', 'Symptom')
    Disease = apps.get_model('expert_system_app', 'Disease')
    DiseaseSymptom = apps.get_model('expert_system_app', 'DiseaseSymptom')
    Treatment = apps.get_model('expert_system_app', 'Treatment')

    for disease_name, data in DISEASES_DATA.items():
        disease, _ = Disease.objects.get_or_create(
            name=disease_name,
            defaults={'description': data['description']}
        )

        for symptom_name, weight in data['symptoms'].items():
            symptom, _ = Symptom.objects.get_or_create(name=symptom_name)
            DiseaseSymptom.objects.get_or_create(
                disease=disease,
                symptom=symptom,
                defaults={'weight': weight}
            )

        for treatment_desc in data['treatments']:
            Treatment.objects.get_or_create(
                disease=disease,
                description=treatment_desc
            )

class Migration(migrations.Migration):

    dependencies = [
        ('expert_system_app', '0002_diseasesymptom_weight'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data),
    ]



